/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiRcaRouteImport } from './routes/api/rca'
import { Route as ApiMaintenanceRouteImport } from './routes/api/maintenance'
import { Route as ApiLessonsRouteImport } from './routes/api/lessons'
import { Route as ApiKnowledgeGraphRouteImport } from './routes/api/knowledge-graph'
import { Route as ApiEntitiesRouteImport } from './routes/api/entities'
import { Route as ApiDocumentsRouteImport } from './routes/api/documents'
import { Route as ApiComplianceGapRouteImport } from './routes/api/compliance-gap'
import { Route as ApiComplianceRouteImport } from './routes/api/compliance'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRcaRoute = ApiRcaRouteImport.update({
  id: '/api/rca',
  path: '/api/rca',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMaintenanceRoute = ApiMaintenanceRouteImport.update({
  id: '/api/maintenance',
  path: '/api/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLessonsRoute = ApiLessonsRouteImport.update({
  id: '/api/lessons',
  path: '/api/lessons',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKnowledgeGraphRoute = ApiKnowledgeGraphRouteImport.update({
  id: '/api/knowledge-graph',
  path: '/api/knowledge-graph',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEntitiesRoute = ApiEntitiesRouteImport.update({
  id: '/api/entities',
  path: '/api/entities',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocumentsRoute = ApiDocumentsRouteImport.update({
  id: '/api/documents',
  path: '/api/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiComplianceGapRoute = ApiComplianceGapRouteImport.update({
  id: '/api/compliance-gap',
  path: '/api/compliance-gap',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiComplianceRoute = ApiComplianceRouteImport.update({
  id: '/api/compliance',
  path: '/api/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/api/chat': typeof ApiChatRoute
  '/api/compliance': typeof ApiComplianceRoute
  '/api/compliance-gap': typeof ApiComplianceGapRoute
  '/api/documents': typeof ApiDocumentsRoute
  '/api/entities': typeof ApiEntitiesRoute
  '/api/knowledge-graph': typeof ApiKnowledgeGraphRoute
  '/api/lessons': typeof ApiLessonsRoute
  '/api/maintenance': typeof ApiMaintenanceRoute
  '/api/rca': typeof ApiRcaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/api/chat': typeof ApiChatRoute
  '/api/compliance': typeof ApiComplianceRoute
  '/api/compliance-gap': typeof ApiComplianceGapRoute
  '/api/documents': typeof ApiDocumentsRoute
  '/api/entities': typeof ApiEntitiesRoute
  '/api/knowledge-graph': typeof ApiKnowledgeGraphRoute
  '/api/lessons': typeof ApiLessonsRoute
  '/api/maintenance': typeof ApiMaintenanceRoute
  '/api/rca': typeof ApiRcaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/api/chat': typeof ApiChatRoute
  '/api/compliance': typeof ApiComplianceRoute
  '/api/compliance-gap': typeof ApiComplianceGapRoute
  '/api/documents': typeof ApiDocumentsRoute
  '/api/entities': typeof ApiEntitiesRoute
  '/api/knowledge-graph': typeof ApiKnowledgeGraphRoute
  '/api/lessons': typeof ApiLessonsRoute
  '/api/maintenance': typeof ApiMaintenanceRoute
  '/api/rca': typeof ApiRcaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/api/chat'
    | '/api/compliance'
    | '/api/compliance-gap'
    | '/api/documents'
    | '/api/entities'
    | '/api/knowledge-graph'
    | '/api/lessons'
    | '/api/maintenance'
    | '/api/rca'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/api/chat'
    | '/api/compliance'
    | '/api/compliance-gap'
    | '/api/documents'
    | '/api/entities'
    | '/api/knowledge-graph'
    | '/api/lessons'
    | '/api/maintenance'
    | '/api/rca'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/api/chat'
    | '/api/compliance'
    | '/api/compliance-gap'
    | '/api/documents'
    | '/api/entities'
    | '/api/knowledge-graph'
    | '/api/lessons'
    | '/api/maintenance'
    | '/api/rca'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiComplianceRoute: typeof ApiComplianceRoute
  ApiComplianceGapRoute: typeof ApiComplianceGapRoute
  ApiDocumentsRoute: typeof ApiDocumentsRoute
  ApiEntitiesRoute: typeof ApiEntitiesRoute
  ApiKnowledgeGraphRoute: typeof ApiKnowledgeGraphRoute
  ApiLessonsRoute: typeof ApiLessonsRoute
  ApiMaintenanceRoute: typeof ApiMaintenanceRoute
  ApiRcaRoute: typeof ApiRcaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rca': {
      id: '/api/rca'
      path: '/api/rca'
      fullPath: '/api/rca'
      preLoaderRoute: typeof ApiRcaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/maintenance': {
      id: '/api/maintenance'
      path: '/api/maintenance'
      fullPath: '/api/maintenance'
      preLoaderRoute: typeof ApiMaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lessons': {
      id: '/api/lessons'
      path: '/api/lessons'
      fullPath: '/api/lessons'
      preLoaderRoute: typeof ApiLessonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/knowledge-graph': {
      id: '/api/knowledge-graph'
      path: '/api/knowledge-graph'
      fullPath: '/api/knowledge-graph'
      preLoaderRoute: typeof ApiKnowledgeGraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/entities': {
      id: '/api/entities'
      path: '/api/entities'
      fullPath: '/api/entities'
      preLoaderRoute: typeof ApiEntitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/documents': {
      id: '/api/documents'
      path: '/api/documents'
      fullPath: '/api/documents'
      preLoaderRoute: typeof ApiDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/compliance-gap': {
      id: '/api/compliance-gap'
      path: '/api/compliance-gap'
      fullPath: '/api/compliance-gap'
      preLoaderRoute: typeof ApiComplianceGapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/compliance': {
      id: '/api/compliance'
      path: '/api/compliance'
      fullPath: '/api/compliance'
      preLoaderRoute: typeof ApiComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiChatRoute: ApiChatRoute,
  ApiComplianceRoute: ApiComplianceRoute,
  ApiComplianceGapRoute: ApiComplianceGapRoute,
  ApiDocumentsRoute: ApiDocumentsRoute,
  ApiEntitiesRoute: ApiEntitiesRoute,
  ApiKnowledgeGraphRoute: ApiKnowledgeGraphRoute,
  ApiLessonsRoute: ApiLessonsRoute,
  ApiMaintenanceRoute: ApiMaintenanceRoute,
  ApiRcaRoute: ApiRcaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
